tipatrello/projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.index, name='index'),
    path('task/<int:task_id>/', views.TaskDetail, name='task-detail'),
    path(
        'task/<int:task_id>/comment/', views.add_comment, name='add_comment'),

]

tipatrello/tipatrello/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls', namespace='projects')),
]

tipatrello/projects/models.py
from django.db import models
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey


class Worker(models.Model):
    "Сотрудники."
    surname = models.CharField(
        'Фамилия',
        max_length=20
    )
    name = models.CharField(
        'Имя',
        max_length=20
    )
    patronymic = models.CharField(
        'Отчество',
        max_length=20
    )
    position = models.CharField(
        'Должность',
        max_length=20
    )

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'

    def __str__(self):
        return f'{self.surname} {self.name} - {self.position}'


class Project(models.Model):
    "Проекты."
    name = models.CharField(
        'Название проекта',
        max_length=200,
    )
    deadline = models.DateField(
        'Срок исполнения',
    )
    description = models.TextField(
        'Описание проекта',
        max_length=500,
    )
    chief = models.ForeignKey(
        Worker,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='project_as_chief',
        verbose_name='Руководитель проекта',
    )
    is_active = models.BooleanField(
        'Статус проекта',
        default=True,
        db_index=True,
    )
    pub_date = models.DateTimeField(
        'Дата создания',
        null=True,
        auto_now_add=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'

    def __str__(self):
        return self.name


class Task(MPTTModel):
    "Задачи."
    TASK_STATUS = [
        ('Новая', 'Новая'),
        ('В работе', 'В работе'),
        ('Закрыта', 'Закрыта'),
    ]
    name = models.CharField(
        'Название задачи',
        max_length=200,
    )
    status = models.CharField(
        'Статус задачи',
        choices=TASK_STATUS,
        default='Новая',
        max_length=10,
    )
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children',
        db_index=True,
        verbose_name='Надзадача'
    )
    description = models.TextField(
        'Описание задачи',
        max_length=500,
        null=True,
        blank=True,
    )
    workers = models.ManyToManyField(
        Worker,
        blank=True,
        related_name='task_and_workers',
        verbose_name='Исполнитель задачи',
    )
    project = models.ForeignKey(
        Project,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='tasks',
        verbose_name='Относится к проекту',
    )
    pub_date = models.DateTimeField(
        'Дата создания',
        null=True,
        auto_now_add=True,
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

    class MPTTMeta:
        order_insertion_by = ['pub_date']

    def get_absolute_url(self):
        return reverse('projects:task-detail', args=[str(self.id)])

    def __str__(self):
        return self.name


class Comment(models.Model):
    """Комментарии к задачам."""
    task = models.ForeignKey(
        Task,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментарий',
    )
    pub_date = models.DateTimeField(
        'Дата создания',
        auto_now_add=True
    )
    text = models.TextField(
        'Текст',
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Комментарий к задаче'
        verbose_name_plural = 'Комментарии к задаче'

    def __str__(self):
        return self.text

tipatrello/projects/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .models import Project, Task
from .form import CommentForm


def index(request):
    "Главная страница со списком проектов."
    template = 'index.html'
    project_list = Project.objects.all()
    context = {
        'page_obj': project_list,
    }

    return render(request, template, context)


def TaskDetail(request, task_id):
    "Страница с детальной информацией о задаче."
    template = 'task_detail.html'
    task = get_object_or_404(
        Task.objects, id=task_id
    )
    form = CommentForm(request.POST or None)
    comments = task.comments.all()

    context = {
        'task': task,
        'comments': comments,
        'form': form,
    }

    return render(request, template, context)


def add_comment(request, task_id):
    "Создание комментария к задаче."
    task = get_object_or_404(Task, id=task_id)
    form = CommentForm(request.POST or None)
    
    comment = form.save(commit=False)
    comment.task = task
    comment.save()

    return redirect('projects:task-detail', task.id)

tipatrello/templates/includes/task_comment_form.html
<div class="card my-4">
  <h5 class="card-header">Добавить комментарий:</h5>
  <div class="card-body">
    <form method="post" action="{% url 'projects:add_comment' task.id %}">
      {% csrf_token %}    
      <div class="form-group mb-2">
        {{ form.text }}
      </div>
      <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
  </div>
</div>

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">      
      <p>
        {{ comment.text }}
      </p>
      <p>{{ comment.pub_date }}</p>
      <hr>
    </div>
  </div>
{% endfor %} 

tipatrello/templates/index.html
{% extends "layout/base.html" %}
{% load mptt_tags %}

{% block title %}Проекты{% endblock %}
{% load cache %}

{% block content %}
{% cache 500 sidebar %}
  {% for project in page_obj %}      
    <div class="container m-3 p-3 border border-dark rounded">
      <div class="row">
        <div class="col">
          <h1>{{project.name|upper}}</h1>
          <p>{{project.description}}</p>
          <strong><u>Руководитель проекта:</u> {{project.chief.surname}} {{project.chief.name}}</strong><br>
          <strong><u>Срок исполнения:</u> {{project.deadline|date:"d.m.Y"}}</strong> 
        </div>
        <div class="col">
          <ul>
            {% recursetree project.tasks.all %}               
              <li>
                <a href="{{node.get_absolute_url}}">{{node.name}} ({{node.status}})</a>
                {% if not node.is_leaf_node %}
                  <ul class="children">
                    {{ children }}
                  </ul>
                {% endif %}
              </li>
            {% endrecursetree %}
          </ul>
        </div>
      </div>           
    </div>             
  {% if not forloop.last %} <hr> {% endif %}
{% endfor %}
{% endcache %} 
{% endblock %}

tipatrello/templates/layout/base.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html> 
<html lang="ru">
  <head>
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">    
    <title>
      {% block title %}Текст на вкладке{% endblock %}
    </title>
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">   
  </head>
  <body class="container-fluid">
    <header class="m-3">
      <h3 class="display-6 text-center"><a href="{% url 'projects:index' %}">Главная</a></h3>
    </header>    
    <div class="container py-5">
    {% block content %}
      Здесь контент
    {% endblock %}
    </div>  
    <footer class="mt-3">
      <p class="text-right font-italic">автор: Клинцова Анастасия Павловна</p>
    </footer>  
  </body>
</html>

tipatrello/templates/task_detail.html
{% extends "layout/base.html" %}
{% load mptt_tags %}

{% block title %}{{task.name}}{% endblock %}

{% block content %}
  <h1>{{task.name|upper}}</h1>  
  <h3> cтатус: {{task.status|lower}} </h3>
  <hr>   
  <p>{{task.description|lower}}</p>
  <hr>
  <div class="col">    
  </div>
  <h4>Ответственные сотрудники:<h4>
  <ul>     
  {% for worker in task.workers.all %}
    <li>{{worker.surname}} {{worker.name}} {{worker.patronymic}} - {{worker.position}}</li>
  {% endfor %}
  </ul> 
  {% include 'includes/task_comment_form.html' %}
{% endblock %}

   